Repository AY2223S2-CS2103T-W14-2/tp, pull requests merged in 2023-03, with the labels that each got.

#82 View Command
  docs/UserGuide.md
  docs/images/charlesWindsor.png
  docs/images/fifthPersonProfile.png
  docs/images/userprofile.png
  docs/team/russelltankaimin.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UserProfilePanel.java
Labels: doc.UserGuide, priority.Medium, new, submission.Team

#118 Tests for View Command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: type.Testing

#121 Deprecate User command
  src/main/java/seedu/address/logic/commands/UserCommand.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/test/java/seedu/address/logic/commands/UserCommandTest.java
  src/test/java/seedu/address/logic/parser/EduMateParserTest.java
Labels: modify, submission.Team

#77 Restructure Developer Guide to Fit Standards
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/AddParserSequenceDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditParserSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/style.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/AddParserSequenceDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ComponentManagers.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditParserSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/add-remark/$Remark.png
  docs/images/add-remark/CommandInterface.png
  docs/images/add-remark/ContextMenu.png
  docs/images/add-remark/CreateTest.png
  docs/images/add-remark/GradleRun.png
  docs/images/add-remark/ParserInterface.png
  docs/images/add-remark/RemarkBound.png
  docs/images/add-remark/RemarkComplete.png
  docs/images/add-remark/RemarkFailureOutput.png
  docs/images/add-remark/RemarkHello.png
  docs/images/add-remark/RemarkNotImplemented.png
Labels: doc.DevGuide

#123 Restructure Developer Guide
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
Labels: doc.DevGuide

#80 Implement Sample Command
  src/main/java/seedu/address/logic/commands/SampleCommand.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/SampleCommandParser.java
  src/main/java/seedu/address/model/util/sampleData.txt
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SampleCommandTest.java
  src/test/java/seedu/address/logic/parser/SampleCommandParserTest.java
Labels: priority.Low, type.Task

#124 Fix sort command by introducing Contact Index
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/IndexHandler.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ContactIndex.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/User.java
  src/main/java/seedu/address/model/person/exceptions/InvalidContactIndexException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/sampleData.txt
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/test/data/JsonEduMateStorageTest/invalidNameEduMate.json
  src/test/data/JsonEduMateStorageTest/invalidNameValidInvalidEduMate.json
  src/test/data/JsonEduMateStorageTest/longModuleTagEduMate.json
  src/test/data/JsonEduMateStorageTest/longModuleTagValidInvalidEduMate.json
  src/test/data/JsonEduMateStorageTest/nonNumericPhoneFieldEduMate.json
  src/test/data/JsonEduMateStorageTest/nonNumericPhoneFieldValidInvalidEduMate.json
  src/test/data/JsonEduMateStorageTest/shortPhoneFieldEduMate.json
  src/test/data/JsonEduMateStorageTest/shortPhoneFieldValidInvalidEduMate.json
  src/test/data/JsonSerializableEduMateTest/duplicatePersonEduMate.json
  src/test/data/JsonSerializableEduMateTest/invalidPersonEduMate.json
  src/test/data/JsonSerializableEduMateTest/typicalPersonsEduMate.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EduMateParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalUser.java
Labels: type.Bug, priority.Medium, type.Testing, new, modify, submission.Team

#126 Add tag and untag command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/main/java/seedu/address/model/person/ModuleTagSet.java
Labels: type.Story

#137 Fix bug in SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/util/sampleData.txt
Labels: type.Bug, severity.High

#139 Add UG and clean up outputs for Tag and Untag
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
Labels: doc.UserGuide, priority.Medium

#134 Tests for ContactIndex changes
  src/main/java/seedu/address/logic/parser/IndexHandler.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EduMateParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/IndexHandlerTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/ContactIndexTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedUserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: severity.Medium, type.Testing, submission.Team

#143 Add elementary tests to tag and untag
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UntagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Labels: type.Testing

#150 Set Contact Index as Default Comparator for Sort
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: priority.Low, modify

#146 Add TOC as sidebar to UG, DG
  docs/_includes/head.html
  docs/_includes/tocDg.html
  docs/_includes/tocUg.html
  docs/_layouts/default.html
Labels: doc.UserGuide, doc.DevGuide

#156 Merge Zichen TOC Changes to DG Branch
  docs/_includes/head.html
  docs/_includes/tocDg.html
  docs/_includes/tocUg.html
  docs/_layouts/default.html
Labels: doc.DevGuide

#157 Update DG for Add, Edit, Sort Command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/DeleteActivityDiagram.puml
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ComponentManagers.png
  docs/images/EditActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: doc.DevGuide

#162 Update DG for Manual Testing Section
  docs/DeveloperGuide.md
Labels: doc.DevGuide

#161 Enable assertions on gradle
  build.gradle
Labels: submission.Team

#172 Change all puml diagrams from png to svg
  docs/DeveloperGuide.md
  docs/images/AddActivityDiagram.svg
  docs/images/AddParserSequenceDiagram.svg
  docs/images/AddSequenceDiagram.svg
  docs/images/ArchitectureDiagram.svg
  docs/images/ArchitectureSequenceDiagram.svg
  docs/images/BetterModelClassDiagram.svg
  docs/images/CommitActivityDiagram.svg
  docs/images/ComponentManagers.svg
  docs/images/DeleteActivityDiagram.svg
  docs/images/DeleteSequenceDiagram.svg
  docs/images/EditActivityDiagram.svg
  docs/images/EditParserSequenceDiagram.svg
  docs/images/EditSequenceDiagram.svg
  docs/images/LogicClassDiagram.svg
  docs/images/ModelClassDiagram.svg
  docs/images/ParserClasses.svg
  docs/images/PersonClassDiagram.svg
  docs/images/StorageClassDiagram.svg
  docs/images/UiClassDiagram.svg
  docs/images/ViewActivityDiagram.svg
  docs/images/tracing/LogicSequenceDiagram.svg
Labels: priority.Medium, doc.DevGuide

#175 Fix formatting errors in puml class diagrams
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ComponentManagers.svg
  docs/images/LogicClassDiagram.svg
  docs/images/ModelClassDiagram.svg
  docs/images/StorageClassDiagram.svg
Labels: priority.High, doc.DevGuide

#174 Modify tag command differently
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ModuleTagSet.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
  src/main/java/seedu/address/model/timetable/Lesson.java
  src/test/java/seedu/address/model/tag/ModuleTagTest.java
Labels: modify

#166 Add DG portion for ViewCommand and Russell's Contribution to Meet Command
  docs/DeveloperGuide.md
  docs/_includes/tocDg.html
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewParserSequenceDiagram.puml
  docs/images/ViewActivityDiagram.png
  docs/images/ViewParserSequenceDiagram.png
Labels: doc.DevGuide, submission.Individual

#178 Restructure UI
  docs/images/Ui.png
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UserProfilePanel.java
  src/main/resources/fonts/Inter/static/Inter-Black.ttf
  src/main/resources/fonts/Inter/static/Inter-Bold.ttf
  src/main/resources/fonts/Inter/static/Inter-ExtraBold.ttf
  src/main/resources/fonts/Inter/static/Inter-ExtraLight.ttf
  src/main/resources/fonts/Inter/static/Inter-Light.ttf
  src/main/resources/fonts/Inter/static/Inter-Medium.ttf
  src/main/resources/fonts/Inter/static/Inter-Regular.ttf
  src/main/resources/fonts/Inter/static/Inter-SemiBold.ttf
  src/main/resources/fonts/Inter/static/Inter-Thin.ttf
  src/main/resources/images/address_book_32.png
  src/main/resources/images/background.png
  src/main/resources/images/edumateLogo.png
  src/main/resources/images/glasses_icon.png
  src/main/resources/images/icon_question.png
  src/main/resources/images/icon_user.png
  src/main/resources/images/icon_x.png
  src/main/resources/images/userpfp.png
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/UserProfilePanel.css
  src/main/resources/view/UserProfilePanel.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: modify

#182 Fix JAR file unable to load data
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/model/location/LocationUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/data/address.txt
  src/main/resources/data/eat.txt
  src/main/resources/data/sampleData.txt
  src/main/resources/data/study.txt
  src/main/resources/data/venues.txt
Labels: type.Bug, priority.High

#179 Update developer guide on Find Command and Key Mappings
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/KeyMapActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/FindActivityDiagram.svg
  docs/images/KeyMapActivityDiagram.png
  docs/images/KeyMapActivityDiagram.svg
  docs/images/ModelClassDiagram.svg
  docs/images/StorageClassDiagram.svg
Labels: doc.DevGuide

#185 Add example use case for find command for UserGuide
  docs/UserGuide.md
Labels: doc.UserGuide

#180 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagram.svg
Labels: doc.DevGuide, submission.Individual

#176 Implement keyboard shortcuts to view previous commands
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/EduMateHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyEduMateHistory.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/EduMateStorage.java
  src/main/java/seedu/address/storage/EduMateStorageManager.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/EduMateStorageManagerTest/invalidNameEduMate.json
  src/test/data/EduMateStorageManagerTest/invalidNameValidInvalidEduMate.json
  src/test/data/EduMateStorageManagerTest/longModuleTagEduMate.json
  src/test/data/EduMateStorageManagerTest/longModuleTagValidInvalidEduMate.json
  src/test/data/EduMateStorageManagerTest/nonNumericPhoneFieldEduMate.json
  src/test/data/EduMateStorageManagerTest/nonNumericPhoneFieldValidInvalidEduMate.json
  src/test/data/EduMateStorageManagerTest/notJsonFormatEduMate.json
  src/test/data/EduMateStorageManagerTest/shortPhoneFieldEduMate.json
  src/test/data/EduMateStorageManagerTest/shortPhoneFieldValidInvalidEduMate.json
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MeetCommandTest.java
  src/test/java/seedu/address/logic/commands/SampleCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UntagCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/IndexHandlerTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/scheduler/SchedulerTest.java
  src/test/java/seedu/address/storage/EduMateStorageManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, type.Story

#187 Fix link in help window
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.Medium

#192 Add assertion in commandBox
  src/main/java/seedu/address/ui/CommandBox.java
Labels: submission.Individual

#193 Add essential functions for Meet Command Integration
  src/main/java/seedu/address/model/commitment/Commitment.java
  src/main/java/seedu/address/model/commitment/Lesson.java
  src/main/java/seedu/address/model/scheduler/Timetable.java
  src/main/java/seedu/address/model/scheduler/time/HourBlock.java
  src/main/java/seedu/address/model/scheduler/time/TimeBlock.java
  src/main/java/seedu/address/model/scheduler/time/TimePeriod.java
  src/main/java/seedu/address/model/scheduler/time/util/TimeUtil.java
  src/main/java/seedu/address/model/util/MathUtil.java
  src/test/java/seedu/address/model/timetable/time/HourBlockTest.java
  src/test/java/seedu/address/model/timetable/time/TimeBlockTest.java
  src/test/java/seedu/address/model/timetable/time/TimetableTest.java
  src/test/java/seedu/address/model/timetable/time/util/TimeUtilTest.java
  src/test/java/seedu/address/model/timetable/util/TypicalTimetable.java
Labels: priority.High, type.Testing

#195 Fix Bugs for Merge Timetable
  src/main/java/seedu/address/model/commitment/Commitment.java
  src/main/java/seedu/address/model/commitment/Lesson.java
  src/main/java/seedu/address/model/scheduler/Timetable.java
  src/main/java/seedu/address/model/scheduler/time/HourBlock.java
  src/main/java/seedu/address/model/scheduler/time/util/TimeUtil.java
  src/test/java/seedu/address/model/timetable/time/TimetableTest.java
  src/test/java/seedu/address/model/timetable/util/TypicalTimetable.java
  src/test/java/seedu/address/model/util/MathUtilTest.java
Labels: type.Bug, priority.High, severity.High

#196 Add test cases for MainApp and AppParameters
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/MainAppTest.java
Labels: type.Testing

#200 Delete file generated during test
  src/test/java/seedu/address/MainAppTest.java
Labels: type.Bug, type.Testing

#204 Final Integration of Meet Command
  missingConfig.json
  src/main/java/seedu/address/logic/recommender/Recommender.java
  src/main/java/seedu/address/logic/recommender/timing/TimingRecommender.java
  src/main/java/seedu/address/logic/recommender/timing/exceptions/CommitmentClashException.java
  src/main/java/seedu/address/model/time/HourBlock.java
  src/main/java/seedu/address/model/time/TimePeriod.java
  src/main/java/seedu/address/model/timetable/Timetable.java
  src/test/java/seedu/address/model/timetable/time/HourBlockTest.java
  src/test/java/seedu/address/model/timetable/time/TimetableTest.java
  src/test/java/seedu/address/model/timingrecommender/TimingRecommenderTest.java
Labels: modify

#205 Integrate Meet Command to UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/model/time/TimePeriod.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetCard.java
  src/main/java/seedu/address/ui/MeetListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetListCard.fxml
  src/main/resources/view/MeetListPanel.fxml
Labels: modify

#206 Fix Bugs in Integration
  src/main/java/seedu/address/logic/parser/IndexHandler.java
  src/main/java/seedu/address/logic/recommender/Recommender.java
  src/main/java/seedu/address/logic/recommender/location/LocationRecommender.java
  src/main/java/seedu/address/logic/recommender/location/LocationTracker.java
  src/main/java/seedu/address/model/location/Location.java
  src/main/java/seedu/address/storage/JsonSerializableEduMate.java
  src/test/data/JsonSerializableEduMateTest/duplicatePersonEduMate.json
  src/test/data/JsonSerializableEduMateTest/invalidPersonEduMate.json
  src/test/java/seedu/address/logic/parser/EduMateParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Bug, severity.High

#81 Implement Save and Load Commands
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoadCommand.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/commands/SampleCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/results/CommandResult.java
  src/main/java/seedu/address/logic/commands/results/ExitCommandResult.java
  src/main/java/seedu/address/logic/commands/results/HelpCommandResult.java
  src/main/java/seedu/address/logic/commands/results/LoadCommandResult.java
  src/main/java/seedu/address/logic/commands/results/SaveCommandResult.java
  src/main/java/seedu/address/logic/commands/results/ViewCommandResult.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/LoadCommandParser.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
  src/main/java/seedu/address/model/location/data/venues 2.txt
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/LoadCommandTest.java
  src/test/java/seedu/address/logic/commands/SaveCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/results/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/results/ExitCommandResultTest.java
  src/test/java/seedu/address/logic/commands/results/HelpCommandResultTest.java
  src/test/java/seedu/address/logic/commands/results/LoadCommandResultTest.java
  src/test/java/seedu/address/logic/commands/results/SaveCommandResultTest.java
  src/test/java/seedu/address/logic/parser/IndexHandlerTest.java
  src/test/java/seedu/address/logic/parser/LoadCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SaveCommandParserTest.java
Labels: priority.Medium, type.Testing, type.Task

#209 Fix bug in updating observable recommendation list
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#211 Allow Long Time Periods for Recommendations
  src/main/java/seedu/address/logic/parser/IndexHandler.java
  src/main/java/seedu/address/logic/recommender/Recommender.java
  src/main/java/seedu/address/logic/recommender/location/LocationTracker.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/recommendation/Recommendation.java
  src/main/java/seedu/address/storage/JsonAdaptedRecommendation.java
Labels: type.Investigate, severity.Medium

#212 Organise Command UI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ScheduledMeetsCard.java
  src/main/java/seedu/address/ui/ScheduledMeetsListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduledMeetsListCard.fxml
  src/main/resources/view/ScheduledMeetsListPanel.fxml
Labels: new

#219 Fix bug for scrolling in Meet List Panel
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetListPanel.fxml
Labels: type.Bug

#216 Update group tag
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/TagType.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/main/java/seedu/address/model/person/GroupTagSet.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/TagCommandTest.java
  src/test/java/seedu/address/logic/commands/UntagCommandTest.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#218 UGDG box rework + Additions to content
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: doc.UserGuide, doc.DevGuide

#223 Extend Timetable to hold 10pm-11pm blocks
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/time/HourBlock.java
  src/main/java/seedu/address/model/time/TimePeriod.java
  src/main/java/seedu/address/model/time/util/TimeUtil.java
  src/main/java/seedu/address/model/timetable/Timetable.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedTimePeriod.java
  src/test/java/seedu/address/model/timetable/time/util/TimeUtilTest.java
  src/test/java/seedu/address/model/timetable/util/TypicalTime.java
  src/test/java/seedu/address/model/timingrecommender/TimingRecommenderTest.java
Labels: modify

#227 Help command summary list
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/data/commandlist.txt
  src/main/resources/data/descriptionlist.txt
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: modify

#230 Reformat feature help command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/data/commandlist.txt
  src/main/resources/data/commandsummary.txt
  src/main/resources/data/descriptionlist.txt
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#225 UGDG add-ons
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/TimetableClass.puml
  docs/images/RecommenderClass.svg
  docs/images/SchedulerActivity.svg
  docs/images/TimeGroup.svg
  docs/images/TimetableClass.svg
  docs/images/ViewActivityDiagram.svg
  docs/images/ViewParserSequenceDiagram.svg
Labels: doc.UserGuide, doc.DevGuide

#232 Relax help window width
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#229 Update developer guide for tests
  docs/DeveloperGuide.md
Labels: doc.DevGuide

#231 Update UG TOC
  docs/_includes/tocUg.html
  docs/_layouts/default.html
  docs/images/Ui.png
Labels: type.Bug

#234 Extend find command to include more prefixes
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: modify

#228 Add Organise Command and Modify UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/commands/OrganiseCommand.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/MeetUpIndexHandler.java
  src/main/java/seedu/address/logic/parser/OrganiseCommandParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/EduMate.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyEduMate.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
  src/main/java/seedu/address/model/meetup/MeetUpIndex.java
  src/main/java/seedu/address/model/meetup/Participants.java
  src/main/java/seedu/address/model/meetup/UniqueMeetUpList.java
  src/main/java/seedu/address/model/meetup/exceptions/DuplicateMeetUpException.java
  src/main/java/seedu/address/model/meetup/exceptions/InvalidMeetUpIndexException.java
  src/main/java/seedu/address/model/meetup/exceptions/MeetUpNotFoundException.java
  src/main/java/seedu/address/model/recommendation/exceptions/DuplicateRecommendationException.java
  src/main/java/seedu/address/storage/EduMateStorageManager.java
  src/main/java/seedu/address/storage/JsonAdaptedMeetUp.java
  src/main/java/seedu/address/storage/JsonAdaptedParticipants.java
  src/main/java/seedu/address/storage/JsonAdaptedRecommendation.java
  src/main/java/seedu/address/storage/JsonAdaptedTimePeriod.java
  src/main/java/seedu/address/storage/JsonSerializableEduMate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetCard.java
  src/main/java/seedu/address/ui/ScheduledMeetsCard.java
  src/main/java/seedu/address/ui/ScheduledMeetsListPanel.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetListCard.fxml
  src/main/resources/view/MeetListPanel.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ScheduledMeetsListCard.fxml
  src/main/resources/view/ScheduledMeetsListPanel.fxml
  src/main/resources/view/UserProfilePanel.css
  src/main/resources/view/UserProfilePanel.fxml
  src/test/data/JsonSerializableEduMateTest/invalidPersonEduMate.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/EduMateTest.java
  src/test/java/seedu/address/storage/JsonSerializableEduMateTest.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: new, modify

#242 Fix bugs for time period
  src/main/java/seedu/address/storage/JsonAdaptedTimePeriod.java
Labels: type.Bug

#239 Improve "You" Language in User Guide
  docs/UserGuide.md
Labels: doc.UserGuide

#237 Update UG for find command and fix bug in command history at boundary
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/EduMateHistory.java
Labels: type.Bug, doc.UserGuide

#238 Reformatting UG
  docs/UserGuide.md
  docs/_includes/tocUg.html
Labels: doc.UserGuide

#247 Modify Help Window UI
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: modify

#249 Implement Unorganise command
  src/main/java/seedu/address/logic/commands/OrganiseCommand.java
  src/main/java/seedu/address/logic/commands/UnorganiseCommand.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/OrganiseCommandParser.java
  src/main/java/seedu/address/logic/parser/UnorganiseCommandParser.java
  src/main/java/seedu/address/model/EduMate.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
  src/main/java/seedu/address/model/meetup/Participants.java
  src/main/java/seedu/address/model/meetup/UniqueMeetUpList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: new

#245 Phase Out NUS from Stations
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/data/stations.txt
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalUser.java
Labels: severity.Medium

#257 Fix Bugs
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, priority.High, severity.High

#254 Update UG for Organise and Unorganise commands
  docs/UserGuide.md
  docs/_includes/tocUg.html
  docs/images/ug_cmds_pics/organise_cmd.png
Labels: doc.UserGuide, submission.Individual

#248 Find command documentation updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: doc.UserGuide

#261 Fix unresponsive add, edit, tag command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
Labels: type.Bug

#266 Fix broken link.
  docs/DeveloperGuide.md
Labels: doc.DevGuide

#265 Add more design features to Up and Down key maps to follow CLI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/EduMateHistory.java
  src/main/java/seedu/address/model/ReadOnlyEduMateHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/model/timetable/time/util/TimeUtilTest.java
Labels: modify

#267 Fix Help Window Not Showing Content Fully.
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, modify

#268 KeyMap and Codecev developer guide update
  docs/DeveloperGuide.md
Labels: doc.DevGuide
