Repository AY2223S2-CS2103T-W14-2/tp, pull requests merged in 2023-04, with the labels that each got.

#323 Fix code-related issues from PED (Russell)
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ContactIndex.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
Labels: type.Bug, severity.Medium, severity.High

#322 Fix PE-D Issues Assigned to Hafeez
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/main/java/seedu/address/logic/commands/SampleCommand.java
  src/main/java/seedu/address/logic/commands/TagCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/commitment/Commitment.java
  src/main/java/seedu/address/model/commitment/Lesson.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/GroupTag.java
  src/main/java/seedu/address/model/tag/ModuleTag.java
  src/main/java/seedu/address/model/time/TimeBlock.java
  src/main/java/seedu/address/model/timetable/Timetable.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/GroupTagTest.java
Labels: type.Bug

#324 Enforce Telegram Handle to have more than 5 characters
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/main/resources/data/sampleData.txt
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#328 Fix duplicate index
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#332 Meet command must have contact index fix
  src/main/java/seedu/address/logic/commands/MeetCommand.java
  src/test/java/seedu/address/logic/commands/MeetCommandTest.java
Labels: type.Bug

#331 Update PPP
  docs/team/seanfirefox.md
Labels: submission.Individual

#325 Fix documentation errors [UG] assigned to Russell
  docs/UserGuide.md
  docs/_config.yml
  docs/_includes/tocUg.html
  docs/images/UG_ui_pictures/HelpWindow.svg
  docs/images/UG_ui_pictures/MeetUpRecommendationPanel.svg
  docs/images/UG_ui_pictures/MeetUpRecommendationUnlabelled.svg
  docs/images/UG_ui_pictures/PersonList.svg
  docs/images/UG_ui_pictures/PersonListCommonMods.svg
  docs/images/UG_ui_pictures/Profile.svg
  docs/images/UG_ui_pictures/ScheduledMeetUpPanel.svg
  docs/images/UG_ui_pictures/ScheduledMeetUpPanelLabelled.png
  docs/images/UG_ui_pictures/command_feedback.png
  docs/images/UG_ui_pictures/command_input_box.png
  docs/images/UG_ui_pictures/ui_labelled.png
  docs/images/UG_ui_pictures/ui_labelled.svg
  docs/images/general_command_format.png
  docs/images/ug_cmds_pics/DeleteCommand.svg
  docs/images/ug_cmds_pics/EditCommand.svg
  docs/images/ug_cmds_pics/FindCommand.svg
  docs/images/ug_cmds_pics/MeetCommand.svg
  docs/images/ug_cmds_pics/OrganiseCommand.svg
  docs/images/ug_cmds_pics/SortCommand.svg
  docs/images/ug_cmds_pics/TagCommand.svg
  docs/images/ug_cmds_pics/UnorganiseCommand.svg
  docs/images/ug_cmds_pics/UntagCommand.svg
  docs/images/ug_cmds_pics/View Command.svg
  docs/images/ug_cmds_pics/addcommand.svg
  docs/index.md
Labels: doc.UserGuide

#335 Update Russell's PPP
  docs/team/russelltankaimin.md
Labels: submission.Individual

#336 Update side ToC DG
  docs/_includes/tocDg.html
Labels: doc.DevGuide

#337 Add checks for empty arguments for Tag and Untag
  docs/team/kennycjy.md
  src/main/java/seedu/address/logic/parser/TagCommandParser.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Labels: type.Bug, submission.Individual

#330 Update DG for Time Period
  docs/DeveloperGuide.md
  docs/_includes/tocDg.html
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TagActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiComponentClassDiagram.puml
  docs/diagrams/UntagActivityDiagram.puml
  docs/images/ModelClassDiagram.svg
  docs/images/StorageClassDiagram.svg
  docs/images/TagActivityDiagram.svg
  docs/images/UiClassDiagram.svg
  docs/images/UiComponentClassDiagram.svg
  docs/images/UntagActivityDiagram.svg
  src/main/java/seedu/address/model/timetable/Timetable.java
Labels: doc.DevGuide

#347 Fix manual testing + missing MSS label in UC12-UC21
  docs/DeveloperGuide.md
  docs/_includes/tocDg.html
Labels: doc.DevGuide

#348 Update Zichen's PPP
  docs/team/zichen-3974.md
Labels: submission.Individual

#349 Rename PersonList to Person List
  docs/DeveloperGuide.md
Labels: doc.DevGuide

#350 Update test cases for Command History
  src/main/java/seedu/address/model/EduMate.java
  src/main/java/seedu/address/model/EduMateHistory.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/EduMateHistoryTest.java
  src/test/java/seedu/address/model/EduMateTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Testing

#351 Create GUI tests
  README.md
  build.gradle
  docs/DeveloperGuide.md
  docs/index.md
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/MeetCardHandle.java
  src/test/java/guitests/guihandles/MeetListPanelHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
  src/test/java/seedu/address/model/recommendation/TypicalRecommendations.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/seedu/address/ui/GuiUnitTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/MeetCardTest.java
  src/test/java/seedu/address/ui/MeetListPanelTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/seedu/address/ui/testutil/StageExtension.java
  src/test/java/seedu/address/ui/testutil/UiPartExtension.java
Labels: type.Testing

#357 Elaborate on Sort Command
  docs/UserGuide.md
Labels: doc.UserGuide

#360 Change colour of tip box and fix spacing in command description in Sort Command
  docs/UserGuide.md
Labels: doc.UserGuide

#359 Fix bug in Save/Load Commands
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/LoadCommand.java
  src/main/java/seedu/address/logic/commands/SaveCommand.java
  src/main/java/seedu/address/logic/parser/LoadCommandParser.java
  src/main/java/seedu/address/logic/parser/SaveCommandParser.java
Labels: type.Bug, doc.UserGuide, severity.Medium

#358 UG/DG fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kennycjy.md
  docs/team/mynameizzhafeez.md
  docs/team/russelltankaimin.md
  docs/team/seanfirefox.md
  docs/team/zichen-3974.md
Labels: doc.UserGuide, doc.DevGuide
