Repository AY2223S2-CS2103T-W14-2/tp, pull requests merged in 2023-02, with the labels that each got.

#32 Person class overhaul
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EduMateParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/EduMate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/User.java
  src/main/java/seedu/address/model/tag/GroupTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/test/data/JsonEduMateStorageTest/invalidAndValidPersonEduMate.json
  src/test/data/JsonEduMateStorageTest/invalidPersonEduMate.json
  src/test/data/JsonSerializableEduMateTest/duplicatePersonEduMate.json
  src/test/data/JsonSerializableEduMateTest/invalidPersonEduMate.json
  src/test/data/JsonSerializableEduMateTest/typicalPersonsEduMate.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EduMateParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/EduMateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableEduMateTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalUser.java
  src/test/java/seedu/address/testutil/UserStub.java
Labels: priority.High, type.Task, modify

#36 Add profile picture for v1.1
  docs/images/russelltankaimin.png
  docs/team/johndoe.md
  docs/team/russelltankaimin.md
Labels: deliverables.Individual

#37 Submit Hafeez's Deliverables for v1.1
  docs/UserGuide.md
  docs/images/mynameizzhafeez.png
  docs/team/mynameizzhafeez.md
Labels: priority.Low, deliverables.Individual

#45 Submit Sean's deliverables for v1.1
  docs/images/seanfirefox.png
  docs/team/seanfirefox.md
Labels: priority.Low, deliverables.Individual

#58 Add User Profile Window
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/UserCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UserProfileWindow.java
  src/main/resources/images/user_icon.png
  src/main/resources/view/UserProfileWindow.css
  src/main/resources/view/UserProfileWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, type.Task, new

#52 Modify Edit Command to Update User Information
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/User.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.Medium, type.Task, modify

#56 Update Developer Guide for v1.1
  docs/DeveloperGuide.md
Labels: priority.Medium, documentation.DeveloperGuide, type.Task, deliverables.Team

#59 Update About Us Page for v1.1
  README.md
  docs/AboutUs.md
  docs/images/kennycjy.png
  docs/images/zichen-3974.png
Labels: priority.Low, type.Task, deliverables.Team

#66 Submit Zichen's deliverables for v1.1
  docs/UserGuide.md
  docs/images/zichen-3974.png
  docs/team/zichen-3974.md
Labels: priority.Low, deliverables.Individual

#70 Remove singleton user
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UserCommand.java
  src/main/java/seedu/address/model/person/User.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedUser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UserProfileWindow.java
  src/test/java/seedu/address/testutil/TypicalUser.java
  src/test/java/seedu/address/testutil/UserStub.java
Labels: priority.High, severity.High, modify, deliverables.Team

#62 Extend find command to search via other fields for v1.2
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/data/JsonSerializableEduMateTest/typicalPersonsEduMate.json
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/EduMateParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/ContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium, type.Testing, modify, type.Story

#73 Update documentation for v1.1
  docs/UserGuide.md
  docs/index.md
Labels: documentation.UserGuide, priority.High, documentation.Index
